## library() calls go here
library(cli)
library(conflicted)
library(countrycode)
library(crew)
library(dotenv)
library(fs)
library(glue)
library(geodata)
# from njtierney/geotargets
library(geotargets)
library(here)
library(janitor)
library(mapview)
library(naniar)
library(randomForest)
library(rsample)
library(rlang)
library(sf)
library(targets)
library(tarchetypes)
library(tidygeocoder)
library(tidymodels)
library(tidyverse)
library(visdat)
library(xgboost)
# from hypertidy/sds
library(sds)
# from hypertidy/dsn
library(dsn)
library(quarto)
