## library() calls go here
library(cli)
library(conflicted)
library(countrycode)
library(crew)
library(dotenv)
library(fs)
library(glue)
library(geodata)
# from njtierney/geotargets
library(geotargets)
library(janitor)
library(mapview)
library(naniar)
library(randomForest)
library(rsample)
library(rlang)
library(sf)
library(targets)
library(tarchetypes)
library(tidygeocoder)
library(tidymodels)
library(tidyverse)
library(visdat)
library(xgboost)
# from hypertidy/sds
library(sds)
# from hypertidy/dsn
library(dsn)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("compare", "terra")
conflict_prefer("extract", "terra")
conflict_prefer("describe", "terra")
conflict_prefer("intersect", "terra")
conflict_prefer("rescale", "terra")
conflict_prefer("trim", "terra")
conflict_prefer("flatten", "purrr")
conflict_prefer("tree", "lobstr")
