#' @title
#' @param data
#' @param new_data
#' @param l_zero_model_list
#' @param l_one_model_setup
#' @return
#' @author njtierney
#' @export
inner_loop <- function(data,
                       new_data = NULL,
                       l_zero_model_list,
                       l_one_model_setup) {
  ir_data_mn_star <- data
  # m_star = Number of rows in each **inner loop** of **genotypic** data
  ir_data_m_star <- ir_data_mn_star %>% filter(type == "genotypic")
  # n_star = Number of rows in each **inner loop** of **phenotypic** data
  ir_data_n_star <- ir_data_mn_star %>% filter(type == "phenotypic")
  # m_star and n_star are generated by the outer loop

  ## generalisation folds
  ## training and out of sample prediction
  train_predict <- vfold_cv(
    data = ir_data_mn_star,
    v = 10
  )

  oos_covariates <- train_predict_zero_level_model(
    train_predict_data = train_predict,
    level_zero_model_list = l_zero_model_list
  )

  # Fit 1 model, for in-sample. 1 time to full dataset, fitting to N*+M* data.
  in_sample_predictions <- predict_out_of_sample_zero_level_models(
    in_sample_data = ir_data_mn_star,
    level_zero_model_list = l_zero_model_list
  )

  in_sample_covariates <- create_in_sample_covariates(
    workflow_list = in_sample_predictions,
    data = new_data,
    n_insecticides = 5
  )

  super_learner_oos <- fit_super_learner(
    ir_data = ir_data_n_star,
    covariate_data = oos_covariates,
    level_one_model_setup = l_one_model_setup
  )

  # Finally, make a prediction, Predict to the N* phenotypic data points
  # To get the in sample predictions. We use the predictions generated by this,
  # once we have determined the parameters of the L1 model
  gp_inla_data_n_star_is_pred <- predict_l1_with_in_sample_covariates(
    in_sample_covariates = in_sample_covariates,
    super_learner_fits = super_learner_oos
  )

  gp_inla_data_n_star_is_pred

}
