#' @title
#' @param data
#' @param new_data
#' @param level_zero_model_list
#' @param level_one_model_setup
#' @return
#' @author njtierney
#' @export
inner_loop <- function(data,
                       new_data = NULL,
                       level_zero_models,
                       level_one_model_setup) {

  ir_data_mn_star <- data
  # m_star = Number of rows in each **inner loop** of **genotypic** data
  ir_data_m_star <- ir_data_mn_star %>% filter(type == "genotypic")
  # n_star = Number of rows in each **inner loop** of **phenotypic** data
  ir_data_n_star <- ir_data_mn_star %>% filter(type == "phenotypic")
  # m_star and n_star are generated by the outer loop

  oos_covariates <- train_predict_level_zero_model(
    train_predict_data = ir_data_mn_star,
    level_zero_models = level_zero_models
  )

  # Fit 1 model, for in-sample. 1 time to full dataset, fitting to N*+M* data.
  in_sample_covariates <- predict_out_of_sample_level_zero_models(
    in_sample_data = ir_data_mn_star,
    level_zero_model_list = level_zero_models,
    new_data = new_data,
    n_insecticides = max(unique(ir_data_mn_star$insecticide_id))
  )

  level_one_oos <- fit_level_one_model(
    ir_data = ir_data_n_star,
    covariate_data = oos_covariates,
    level_one_model_setup = level_one_model_setup
  )

  # Finally, make a prediction, Predict to the N* phenotypic data points
  # To get the in sample predictions. We use the predictions generated by this,
  # once we have determined the parameters of the L1 model
  # is = in sample
  gp_inla_data_n_star_is_pred <- predict_level_one_with_in_sample_covariates(
    in_sample_covariates = in_sample_covariates,
    level_one_fits = level_one_oos
  )

  gp_inla_data_n_star_is_pred

}
