#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title
#' @param data
#' @param l_zero_model_formula
#' @param l_zero_model_list
#' @return
#' @author njtierney
#' @export
inner_loop <- function(data,
                       new_data,
                       l_zero_model_formula,
                       l_zero_model_list,
                       l_one_model_setup) {

  ir_data_mn_star <- data
  # m_star = Number of rows in each **inner loop** of **genotypic** data
  ir_data_m_star <- ir_data_mn_star %>% filter(type == "genotypic")
  # n_star = Number of rows in each **inner loop** of **phenotypic** data
  ir_data_n_star <- ir_data_mn_star %>% filter(type == "phenotypic")
  # m_star and n_star are generated by the outer loop

  # 10 times to get the 10 folds out of sample predictions
  ## The generalisation step
  ## -- Check the generalisation paper for terminolgoy
  # Train on 90% ((N* + M*) x 0.9), predict on 10% (N* x 0.1)

  ## generalisation folds
  ## training and out of sample prediction
  train_predict <- create_train_predict(
    data = ir_data_mn_star,
    # so we get equal test/training within type
    strata = type,
    n_folds = 10
  )

  # this should be N* + M*
  train_data_mn_star <- extract_training(train_predict)
  # this should just be N*
  predict_data_nstar <- extract_predict(train_predict) %>%
    filter(type == "phenotypic")

  # this should fit 10 models - preparing for out of sample (oos)
  zero_level_oos_mn_star <- fit_zero_level_models(
    data = train_data_mn_star,
    formula = l_zero_model_formula,
    models = l_zero_model_list
  )

  # these prediction vectors should happen on each list of `predict_data`
  # these will be of length N*
  out_of_sample_predictions <- predict_models(
    data = predict_data_nstar,
    models = zero_level_oos_mn_star
    # TODO: ensure that the output is an SF object, so we retain the coordinates
  )

  # this should fit 1 model, for in-sample
  # 1 time to the full dataset, fitting to N*+M* data.
  zero_level_in_sample <- fit_zero_level_models(
    # this is being fit to the
    data = ir_data_mn_star,
    formula = l_zero_model_formula,
    models = l_zero_model_list
  )

  # ---- the L1 models ---- #
  # Take the out of sample predictions for each of the models,
  # combine them together of length N*, into the fixed effects,
  # one per model (XBG, RF, BGAM)
  # A 3xN* matrix / AKA out of sample covariates?
  out_of_sample_covariates <- combine_predictions(
    out_of_sample_predictions
  )

  # Fit the whole L1 model to N* original data, using out of sample covariates
  gp_inla_data_n_star_oos <- build_inla_data(
    ir_data = ir_data_n_star,
    # including the out of sample covariates
    covariate_data = out_of_sample_covariates
  )

  # Fit the whole L1 model to N* original data, using out of sample covariates
  # oos = out of sample
  # super learner = L1 model
  super_learner_oos <- gp_inla(data = gp_inla_data_n_star_oos,
                               setup = l_one_model_setup)

  # Finally, we make a prediction ----
  # Predict to the N* phenotypic data points, to get the in sample predictions
  # We use the predictions generated by this,
  # once we have determined the parameters of the L1 model
  in_sample_predictions <- predict_models(
    # the new environmental covariates
    data = new_data,
    models = zero_level_in_sample
  )

  in_sample_covariates <- combine_predictions(
    in_sample_predictions
  )

  # But we switch out-of-sample L0 covariates for L0 **in-sample covariates**
  # that gives a prediction of length N*
  gp_inla_data_n_star_is <- predict(
    model = super_learner_oos,
    data = in_sample_covariates
  )

  return(
    gp_inla_data_n_star_is
  )


}
